name: value_stories_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  # purchases_flutter: 
  # change_app_package_name:

  provider: any                        #USED FOR STATE MANAGEMENT IN OUR APP
  dots_indicator: any                   #USED FOR  THE WORM DESIGN LIKE INDICATOR  
  smooth_page_indicator: any
  # flutter_html:
  simple_html_css: any
  # flutter_rating_bar: ^3.0.1+1            #USED FOR RATING STARS
  # modal_progress_hud_nsn: 0.1.0-nullsafety-1              #USED FOR ASYNCHRONOUS PURPOSES

  
  # firebase_database: ^6.0.0
#   firebase_auth: ^0.18.1+2
#   firebase_crashlytics: ^0.2.1+1
  cloud_firestore: any
  # image_picker: ^0.8.0+1
  # image_crop: ^0.4.0
  # image_cropper: ^1.3.1
  # tflite: ^1.1.2
  # crop_your_image: ^0.5.1+1
#   dio: ^3.0.10
#   dio_http_cache: ^0.2.11
  get: any
  get_it: any
  fluid_bottom_nav_bar: any
  flutter_screenutil: any
  avatar_glow: any
  flutter_spinkit: any
  in_app_purchase: ^2.0.1
  image_picker: any
  file_picker: any
  cached_network_image: any
  just_audio: any
  audio_video_progress_bar: any
    
  # audioplayers:
    

    
  #Backend plugins
  firebase_auth: any
  firebase_storage: any
  shared_preferences: any
  firebase_core:  any



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/static_assets/
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600

    - family: Leiko
      fonts:
        - asset: assets/fonts/Leiko-Regular.otf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
